# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'app_travel' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for app_travel
pod 'ImagePicker'
pod 'QBImagePickerController'
pod 'GoogleMaps'
pod 'SnapKit'
pod 'RxSwift'
pod 'RxCocoa'
pod 'FacebookCore'
pod 'FacebookLogin'
pod 'FacebookShare'
pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'Firebase/Core'
pod 'Firebase/Storage'
pod 'Firebase/Database'

end
